"""Snapshot the production device code for a small, isolated occupancy experiment."""
import hashlib
import argparse
import json
from pathlib import Path
from mfe_probe_source import read_device_body

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / 'mfq/kernels/cuda/mfe_ffn.cu'
parser=argparse.ArgumentParser()
parser.add_argument('--compact',action='store_true')
args=parser.parse_args()
OUTPUT = Path(__file__).with_name('mfe_gu_'+('compact' if args.compact else 'register')+'_probe_body.inc')
raw = SOURCE.read_bytes() + (ROOT / 'mfq/kernels/cuda/mfe_ffn_device.cuh').read_bytes()
body = read_device_body(ROOT)
old = '''template<int MinimumBlocks,bool Grouped,uint32_t Formats=0x3fffeu,bool DefaultMath=false,bool E8Narrow=false>
__global__ void __launch_bounds__(512,MinimumBlocks) mfe_ffn_parallel_gate_up_kernel'''
new = '''template<int MinimumBlocks,bool Grouped,uint32_t Formats=0x3fffeu,bool DefaultMath=false,bool E8Narrow=false,int MaximumThreads=512>
__global__ void __launch_bounds__(MaximumThreads,MinimumBlocks) mfe_ffn_parallel_gate_up_kernel'''
assert body.count(old) == 1
body = body.replace(old, new) + '\n} // anonymous namespace\n} // namespace mfq::cuda\n'
if args.compact:
    for field in ('e8_dense_groups','d4_dense_groups'):
        old='if(d.'+field+')'
        assert body.count(old)==2
        body=body.replace(old,'if constexpr(true)')
digest = hashlib.sha256(raw).hexdigest()
OUTPUT.write_text('// Generated by generate_mfe_gu_register_probe.py; source SHA256: '+digest+'\n'+body,
                  encoding='utf-8', newline='\n')
print(json.dumps(dict(source_sha256=digest, output=str(OUTPUT),
                      output_sha256=hashlib.sha256(OUTPUT.read_bytes()).hexdigest())))
