import { expect, test } from '@playwright/test';
import { mockStudioServer } from './mockServer';
import { analysisArtifacts, analysisFixture } from '../tests/fixtures/checkpointAnalysis';

test('checkpoint analysis charts and controls fit desktop and mobile', async ({ page }, testInfo) => {
  await mockStudioServer(page);
  await page.route(/\/api\/v1\/models(?:\?.*)?$/, route => route.fulfill({ json: { data: analysisArtifacts } }));
  await page.route('**/api/v1/models/*/analysis', route => route.fulfill({ json: analysisFixture(route.request().url().includes(analysisArtifacts[1].id)) }));
  await page.goto('/analysis');
  await expect(page.getByRole('heading', { name: 'Model structure' })).toBeVisible();
  await expect(page.locator('.kv-cache-planner')).not.toHaveAttribute('open', '');
  await page.locator('.kv-cache-planner > summary').click();
  await expect(page.getByRole('row', { name: /QSA total cache/ })).toBeVisible();
  await expect(page.getByRole('row', { name: /^Indexer cache/ })).toBeVisible();
  await expect(page.locator('[data-cache-curve]')).toHaveCount(3);
  await page.getByRole('button', { name: 'ctx 8192' }).click();
  await expect(page.getByRole('spinbutton', { name: 'Expected ctx' })).toHaveValue('8192');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('analysis-kv-cache.png'), fullPage: true });
  await page.locator('.kv-cache-planner > summary').click();
  await expect(page.locator('.analysis-advanced')).not.toHaveAttribute('open', '');
  await page.locator('.analysis-advanced > summary').click();
  await expect(page.locator('.analysis-advanced')).toHaveAttribute('open', '');
  await expect(page.getByText('Expert hidden size', { exact: true })).toBeVisible();
  await expect(page.getByText('GR bottleneck dimension', { exact: true })).toBeVisible();
  await expect(page.getByText('Router activation', { exact: true })).toBeVisible();
  await expect(page.getByText('Router weight normalization', { exact: true })).toHaveCount(0);
  await expect(page.locator('.analysis-normalizations').first()).toContainText('GroupedRMSNorm');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('analysis-advanced.png'), fullPage: true });
  await expect(page.locator('.architecture-schedule')).toHaveText('3 × [3 × GDN → QSA]');
  await page.getByRole('button', { name: 'Inspect GDN', exact: true }).click();
  await expect(page.getByRole('img', { name: 'GDN · architecture detail' })).toBeVisible();
  const expand = page.getByRole('button', { name: 'Expand architecture', exact: true });
  await expand.click();
  const dialog = page.getByRole('dialog', { name: 'Architecture details' });
  await expect(dialog).toBeVisible();
  if (testInfo.project.name === 'desktop') expect((await dialog.boundingBox())!.width).toBeGreaterThan(800);
  await dialog.getByRole('tab', { name: 'QSA', exact: true }).click();
  await expect(dialog.getByText('Top-k blocks', { exact: true })).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(dialog).toBeHidden();
  await expect(expand).toBeFocused();
  await page.locator('.analysis-architecture').getByRole('tab', { name: 'Overview', exact: true }).click();
  await expect(page.locator('.expert-heatmap canvas')).toHaveCount(4);
  await expect(page.locator('.expert-heatmap .precision-chart-average')).toHaveCount(4);
  await expect(page.locator('.layer-budget .budget-line')).toHaveCount(3);
  await expect(page.locator('.budget-legend')).toContainText('MoEAttentionTotal');
  await page.getByRole('button', { name: 'GiB', exact: true }).click();
  await expect(page.getByRole('button', { name: 'GiB', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: 'bpw', exact: true }).click();
  const canvas = page.locator('.expert-heatmap canvas').first();
  expect(await canvas.evaluate((element: HTMLCanvasElement) => {
    const context = element.getContext('2d')!;
    return Array.from({ length: element.height / 7 }, (_, layer) => {
      const pixels = context.getImageData(0, layer * 7, 1, 7).data;
      return Array.from({ length: 7 }, (_, row) => [0, 1, 2].every(channel => pixels[row * 4 + channel] === pixels[channel])).every(Boolean);
    }).every(Boolean);
  })).toBe(true);
  const bounds = await canvas.boundingBox();
  await canvas.click({ position: { x: bounds!.width * 0.5, y: bounds!.height * 0.5 } });
  await expect(page.locator('.chart-readout').first()).toContainText('bpw');
  await page.screenshot({ path: testInfo.outputPath('analysis-experts.png'), fullPage: true });
  await page.getByRole('tab', { name: 'Attention & projections' }).click();
  await expect(page.getByRole('combobox', { name: 'Select projection' })).toBeVisible();
  await page.getByRole('combobox', { name: 'Select projection' }).selectOption('gdn:qkv');
  await expect(page.getByRole('img', { name: 'qkv per-layer bpw bar heatmap' })).toBeVisible();
  await expect(page.locator('.projection-bars .precision-chart-average')).toHaveText('Average 5.200 bpw');
  await page.getByRole('combobox', { name: 'Select model' }).selectOption(analysisArtifacts[1].id);
  await expect(page.locator('.analysis-fact-architecture')).toContainText('qwen3_5');
  await expect(page.locator('.kv-cache-planner')).not.toHaveAttribute('open', '');
  await page.locator('.kv-cache-planner > summary').click();
  await expect(page.getByRole('row', { name: /GQA total cache/ })).toBeVisible();
  await expect(page.getByRole('spinbutton', { name: 'Expected ctx' })).toHaveValue('4096');
  await expect(page.locator('.kv-cache-planner').getByRole('row', { name: /QSA|GDN|PLE|Indexer/ })).toHaveCount(0);
  await expect(page.locator('.architecture-tabs').getByRole('tab', { name: 'GQA', exact: true })).toBeVisible();
  await page.locator('.analysis-advanced > summary').click();
  await expect(page.locator('.analysis-advanced').getByRole('heading', { name: 'GQA', exact: true })).toBeVisible();
  await expect(page.locator('.architecture-tabs').getByRole('tab', { name: 'GR', exact: true })).toHaveCount(0);
  await expect(page.locator('.architecture-tabs').getByRole('tab', { name: 'PLE', exact: true })).toHaveCount(0);
  await page.getByRole('tab', { name: 'Routed experts' }).click();
  await expect(page.locator('.analysis-empty-chart')).toContainText('No routed expert precision metadata');
  await page.getByRole('combobox', { name: 'Select model' }).selectOption(analysisArtifacts[2].id);
  await expect(page.getByRole('alert')).toContainText('Model shards are incomplete');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
